<?php
/**
 * Plugin Name:       ElasticPress Proxy
 * Description:       A custom PHP Proxy to handle Instant Results requests.
 * Version:           1.2.0
 * Author:            10up | ElasticPress.io
 * Author URI:        https://elasticpress.io
 * Text Domain:       elasticpress-proxy
 * Domain Path:       /languages
 * Update URI:        https://github.com/10up/elasticpress-proxy
 * Requires at least: 5.6
 * Requires PHP:      7.0
 * License:           GPL v2 or later
 * License URI:       https://www.gnu.org/licenses/gpl-2.0.html
 *
 * @package ElasticPress_Custom_Proxy
 */

namespace ElasticPress_Custom_Proxy;

use ElasticPress\Indexables;
use ElasticPress\Utils;

defined( 'ABSPATH' ) || exit;

/**
 * Enable the Instant Results feature.
 */
add_filter( 'ep_instant_results_available', '__return_true' );

/**
 * Save the a PHP file with the search query template and the post index URL into the uploads folder.
 *
 * @param string $search_template The search template.
 */
function save_template( $search_template ) {
	global $wp_filesystem;

	$post_index     = Indexables::factory()->get( 'post' )->get_index_name();
	$post_index_url = trailingslashit( Utils\get_host( true ) ) . $post_index;

	require_once ABSPATH . '/wp-admin/includes/file.php';
	WP_Filesystem();

	$file_content = [
		'<?php',
		'// This file is automatically generated. DO NOT MODIFY IT.',
		'$post_index_url = \'' . $post_index_url . '\';',
		'$query_template = \'' . $search_template . '\';',
		'',
	];

	$file_content = implode( "\n", $file_content );

	$wp_filesystem->put_contents(
        trailingslashit( WP_CONTENT_DIR ) . 'uploads/ep-custom-proxy.php',
        $file_content
	);
}
add_action( 'ep_instant_results_template_saved', __NAMESPACE__ . '\save_template' );

/**
 * Set the custom proxy as the search endpoint.
 *
 * @return string
 */
function set_proxy() {
	return content_url( 'proxy.php' );
}
add_filter( 'ep_instant_results_search_endpoint', __NAMESPACE__ . '\set_proxy' );

/**
 * Function to copy stub file to content directory after install.
 *
 * Called by Composer
 *
 * @return bool
 */
function copy_stub_file() {
    $source = plugin_dir_path( __FILE__ ) . 'stubs/proxy.php';
    $destination = WP_CONTENT_DIR . '/proxy.php';

    if ( ! copy( $source, $destination ) ) {
        echo "Failed to copy proxy file to content directory.\n";
        return false;
    }

    echo "Successfully copied proxy file to content directory.\n";
    return true;
}